apiVersion: v1
kind: Service
metadata:
    name: wildflyspringbootdemo
spec:
    type: ClusterIP
    ports:
    - name: web
      port: 8080 
    - name: admin
      port: 9990
    selector:
        app: wildflyspringbootdemo
